### ISSUE TITLE
Add functionality to start psc-ide-server?

### ISSUE THREAD

**Issue by anttih** [kritzcreek/purescript-psc-ide#10]
Currently I'm using the same (shamelessly stolen) code from pscid which starts the server in an experimental branch of psc-pane. It could be great if we could share the code.

**Comment by kritzcreek** [comment]
What you found in `pscid` is in turn a dumbed down version of [ide-purescript](https://github.com/nwolverson/purescript-ide-purescript-core/blob/b0823a90965a41c5acd1352bfd632aac94bac9bd/src/IdePurescript/PscIdeServer.purs) code. I think we'll want to find the right level of sophistication and flexibility for all our three usecases.

**Comment by nwolverson** [comment]
I'm now also using node-which to find the executable, to address 2 issues
- Could be `.cmd` or `.exe` on windows
- Warn if there are multiple `psc-ide-server` versions on the path (and log versions etc)

I wonder if this would be relevant to others, maybe it's less easy to share as there is an npm dependency but at the least could extract the which bindings (I know pulp is using this too to find `psa`)

**Comment by kritzcreek** [comment]
The user base for this library is probably going to stay very small and specialized so I'm not too worried about a bit of setup (node dep). 

Sounds awesome I want it! :+1: Do you want to PR it or should I port it over? Where should I look in that case?

**Comment by nwolverson** [comment]
I may as well make a PR, I have a few thoughts & can make sure it still works for me... Will try and take a look tonight

**Comment by anttih** [comment]
Oh I did not know about purescript-ide-purescript-core. It also wraps the JSON output which I think could also be used in this project (and in psc-pane).

What about multi-project support? There was some talk about it somewhere, can't remember, but maybe one option would be to just try a range of ports when starting the server?

**Comment by kritzcreek** [comment]
@anttih https://github.com/purescript/roadmap/issues/51 <- multiproject discussion

**Comment by anttih** [comment]
@kRITZCREEK thanks!

Ok, so the dependencies are the other way around: purescript-ide-purescript-core depends on this project. But I'm a little confused, what's the relationship between the two? Both have some similar JSON parsing code, for example.

**Comment by kritzcreek** [comment]
purescript-ide-purescript-core is code that can be shared between the atom and the vs-code plugin. The reason it has error parsing code, is that it used the json errors from the compiler. With the very recent addition of rebuild for `psc-ide` we now also get json-errors in that context which is why the parsing functionality is duplicated between the two.

Might be worth unifying the error parsing

**Comment by nwolverson** [comment]
Just typed out exactly what @kRITZCREEK said... I'd be up for pushing things which are related to psc-ide and have wider use to here.

**Comment by kritzcreek** [comment]
Fixed by #11
