### ISSUE TITLE
Support --polling parameter

### ISSUE THREAD

**Issue by cebaa** [kritzcreek/purescript-psc-ide#31]
https://github.com/purescript/purescript/issues/2249, on Windows we need this to lower the CPU usage, need to start `purs ide server --pooling`. https://github.com/kRITZCREEK/purescript-psc-ide/blob/master/src/PscIde/Server.purs does not support this now, except watch | !watch.

**Comment by kritzcreek** [comment]
Do you maybe want to submit a PR? I think it's fine to just add a Boolean to the server args and add it to the command pretty printer.
