### ISSUE TITLE
Parse suggestions

### ISSUE THREAD

**Issue by anttih** [kritzcreek/purescript-psc-ide#32]
Parse suggestions and add to `RebuildError`.

**Comment by nwolverson** [comment]
Oh, just realised I'm not using `RebuildError` from here but I have some other version of psc errors/parsing. I should rediscover why and merge into here.

**Comment by kritzcreek** [comment]
I think we're (me for pscid) using psa's error parser.

**Comment by nwolverson** [comment]
Maybe a dependency on https://github.com/natefaubion/purescript-psa-utils would make sense then?

**Comment by anttih** [comment]
I saw the psa-utils but thought it would make sense to have it implemented here. I mean, shouldn't the dependency be the other way around?

**Comment by nwolverson** [comment]
Pulling the compiler error types into an independent package might make sense. psa-utils only uses them from actual compiler output, this package actually uses them from IDE server output, the only overlap is really the error types.

@natefaubion ?

**Comment by nwolverson** [comment]
Fixed in fc4c83771332dd5606c0fb752e9d60bd9067b250
