### ISSUE TITLE
Large responses lost

### ISSUE THREAD

**Issue by nwolverson** [kritzcreek/purescript-psc-ide#4]
Large responses will result in multiple `data` events on the socket, the current code attempts to parse the initial prefix as JSON and fails. Should accumulate and parse the entire input.

I wonder if it's worth pulling out a node/socket library or at least building on top of `purescript-node-streams`.

**Comment by kritzcreek** [comment]
The problem with purescript-node-streams is that they are missing the onConnect event... They also seemed to be racy. When I tried accumulating the 'data' events in a buffer I got the close event before all the data was collected... One possibility could be to make the socket linebuffered.

**Comment by nwolverson** [comment]
OK, I thought the `end` event might work but as I read up it doesn't sound great, in this case could just wait for the first newline.

(For reference it was a pursuit response that was large, over 4k-ish chars).

**Comment by kritzcreek** [comment]
fixed in #7
